name: rikardnilsson
favicon: null
layout_spectrum: 0.4133188652340323
typography_spectrum: 0.7307267212308943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4318992132321
  lightness: 0.03406035341322422
  saturation: 0.45527439657598734
  rhythmicContrast: 0.997969830641523
purpose: []
